name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git zip unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf libtool \
          libffi-dev
      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses || true
          yes | sdkmanager "build-tools;33.0.2" "platforms;android-33" || true
      - name: Install buildozer
        run: |
          pip install buildozer==1.5.0 cython==0.29.33
      - name: Build APK
        run: |
          yes | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LeapYear
          path: bin/*.apk
