name: Build APK
on:
  push:
    branches: [ main ]
env:
  FLET_CLI_NO_RICH_OUTPUT: 1
  PYTHONUTF8: 1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Flet
        run: pip install flet
      - name: Build APK
        run: flet build apk --yes --verbose
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: 简约闰年查询
          path: build/apk/*.apk
